version: '2.1'

services:
    server:
        build:
            context: docker-files/server
        ports:
            - 4000:80
        mem_limit: 1024MB
        cpu_shares: 256

    agent:
        build:
            context: docker-files/agent
        links:
          - server:server
        environment:
            SERVER_URL: http://server/work/
            LOCATION: Test
        ports:
            - 4001:80
        mem_limit: 1024MB
        cpu_shares: 256